2019-05-10 23:30:34,883 ERROR: Exception on /online3d [GET] [in c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Jager\Flask\microblog\app\main\routes.py", line 155, in online3d
    return render_template('Online3DViewer-master/embeddable/fullsceen.html')
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Online3DViewer-master/embeddable/fullsceen.html
2019-05-10 23:31:44,450 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:31:49,899 ERROR: Exception on /online3d [GET] [in c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Jager\Flask\microblog\app\main\routes.py", line 155, in online3d
    return render_template('Online3DViewer-master/embeddable/fullsceen.html')
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Online3DViewer-master/embeddable/fullsceen.html
2019-05-10 23:37:07,355 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:38:11,219 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:38:52,041 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:38:54,006 ERROR: Exception on /online3d [GET] [in c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Jager\Flask\microblog\app\main\routes.py", line 155, in online3d
    return render_template('another/try/trial.html')
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\jager\flask\microblog\myenv\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: another/try/trial.html
2019-05-10 23:39:14,885 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:39:53,648 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
2019-05-10 23:40:49,219 INFO: Microblog startup [in C:\Users\Jager\Flask\microblog\app\__init__.py:77]
